trigger:
- main

pool:
  name: Default

stages:
  - stage:
    jobs:
      - job: sanjay
        displayName: init and validate
        steps:
          - task: TerraformTask@5
            displayName: 'Terraform init'
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: 'YamlSRC'
              backendAzureRmStorageAccountName: 'sanjaystorage4040'
              backendAzureRmContainerName: 'sanjaycontainer'
              backendAzureRmKey: 'sanjay.tfsate'
          - task: TerraformTask@5
            displayName: 'Terraform Validate'
            inputs:
              provider: 'azurerm'
              command: 'validate'
          - task: TerraformTask@5
            displayName: 'Terraform plan'
            inputs:
              provider: 'azurerm'
              command: 'plan' 
              environmentServiceNameAzureRM: 'YamlSRC'
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'apply'
              environmentServiceNameAzureRM: 'YamlSRC'
