trigger:
- main

pool:
  name: MangoAgent

steps:
- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'ServiceConnection'
    backendAzureRmStorageAccountName: 'sanjaysingraur3'
    backendAzureRmContainerName: 'sanjaycontainer3'
    backendAzureRmKey: 'mango.tfstate'
