trigger:
- main

pool:
  name: Default

stages:
  - stage: 'terraform_nit'
    jobs:
      - job: sanjay
        displayName: init and validate
        steps:
          - task: TerraformTask@5
            displayName: 'Terraform init'
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: 'YamlSRC'
              backendAzureRmStorageAccountName: 'sanjaystorage4040'
              backendAzureRmContainerName: 'sanjaycontainer'
              backendAzureRmKey: 'sanjay.tfsate'
          - task: TerraformTask@5
            displayName: 'Terraform Validate'
            inputs:
              provider: 'azurerm'
              command: 'validate'
      - job:
        dependsOn: sanjay
        displayName: terrafom plan
        steps:
          - task: TerraformTask@5
            displayName: 'Terraform init'
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: 'YamlSRC'
              backendAzureRmStorageAccountName: 'sanjaystorage4040'
              backendAzureRmContainerName: 'sanjaycontainer'
              backendAzureRmKey: 'sanjay.tfsate'
          - task: TerraformTask@5
            displayName: 'Terraform plan'
            inputs:
              provider: 'azurerm'
              command: 'plan' 
              environmentServiceNameAzureRM: 'YamlSRC'
      
