trigger:
- main

pool:
  name: MangoAgent

steps:
- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'ServiceConnection'
    backendAzureRmStorageAccountName: 'sanjaysingraur'
    backendAzureRmContainerName: 'sanjaycontainer'
    backendAzureRmKey: 'mango.tfstate'
