trigger:
- main

pool:
  name: MangoAgent

steps:
-
- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'serviceconnection3'
    backendAzureRmStorageAccountName: 'sanjaystorage4040'
    backendAzureRmContainerName: 'sanjaycontainer'
    backendAzureRmKey: 'sanjay.tfstate'