trigger:
- main

pool:
  name: Default

steps:

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'YamlSRC'
    backendAzureRmStorageAccountName: 'sanjaystorage4040'
    backendAzureRmContainerName: 'sanjaycontainer'
    backendAzureRmKey: 'sanjay.tfstate'
